New init script and configuration file #3

diff --git a/scripts/cmake/electrosense b/scripts/cmake/electrosense
--- a/scripts/cmake/electrosense
+++ b/scripts/cmake/electrosense
@@ -1,50 +1,70 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          electrosense
+# Provides:          <NAME>
 # Required-Start:    $local_fs $network $named $time $syslog
 # Required-Stop:     $local_fs $network $named $time $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Description:       electrosense script
+# Description:       <DESCRIPTION>
 ### END INIT INFO
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
+SCRIPT=/etc/electrosense/run.sh
+RUNAS=root
 
-. /lib/lsb/init-functions
+PIDFILE=/var/run/script.pid
+LOGFILE=/var/log/script.log
 
 
-DAEMON="/etc/electrosense/run.sh"
-RUNAS="root"
+start() {
+  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo -n '[*] Starting service ... ' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+  echo ' OK ' >&2
+}
 
-PIDFILE="/var/run/electrosense.pid"
-LOGFILE="/var/log/electrosense.log"
+stop() {
+  #if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+  #  echo 'Service not running' >&2
+  #  return 1
+  #fi
+  echo -n '[*] Stopping service ... ' >&2
+  sudo killall -9 run_gpu_sensor
+  #kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo ' OK ' >&2
+}
+
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+    update-rc.d -f <NAME> remove
+    rm -fv "$0"
+  fi
+}
 
 case "$1" in
-start)  
-	echo "Start"
-        log_daemon_msg "Starting scanning spectrum" "electrosense"
-        start_daemon -p $PIDFILE $DAEMON 
-        log_end_msg $?
-        ;;
-stop)   log_daemon_msg "Stopping scanning spectrum" "electrosense"
-        #killproc -p $PIDFILE $DAEMON
-	sudo killall -9 run_gpu_sensor
-        RETVAL=$?
-        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
-        log_end_msg $RETVAL
-        ;;
-restart) log_daemon_msg "Restarting periodic command scheduler" "electrosense"
-        $0 stop
-        $0 start
-        ;;
-status)
-        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
-        ;;
-*)      log_action_msg "Usage: /etc/init.d/cron {start|stop|status|restart|reload|force-reload}"
-        exit 2
-        ;;
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  restart)
+    stop
+    start
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|uninstall}"
 esac
-exit 0
-
-
 
